[features]
seeds = false
skip-lint = false

[programs.localnet]
datasov_solana = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
datasov_identity = "DataSovIdentity11111111111111111111111111111"

[programs.devnet]
datasov_solana = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
datasov_identity = "DataSovIdentity11111111111111111111111111111"

[programs.mainnet]
datasov_solana = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
datasov_identity = "DataSovIdentity11111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
validator_configs = [
    { limit_ledger_size = 50000000 }
]
